# TauriMule - Script de importación de configuración de eMule a aMule
Write-Host "Buscando instalación y configuración de eMule..." -ForegroundColor Cyan

$emulePaths = @(
    "$env:LOCALAPPDATA\eMule\config",
    "$env:APPDATA\eMule\config",
    "C:\Program Files (x86)\eMule\config",
    "C:\Program Files\eMule\config"
)

$srcDir = $null
foreach ($p in $emulePaths) {
    if (Test-Path (Join-Path $p "preferences.ini")) {
        $srcDir = $p
        break
    }
}

if (-not $srcDir) {
    Write-Host "No se encontró el directorio de configuración de eMule." -ForegroundColor Red
    exit 1
}

$destDir = "$env:APPDATA\aMule"
if (-not (Test-Path $destDir)) {
    New-Item -ItemType Directory -Force -Path $destDir | Out-Null
}

Write-Host "Origen: $srcDir" -ForegroundColor Green
Write-Host "Destino: $destDir" -ForegroundColor Green

# 1. Copiar archivos binarios compatibles
$files = @(
    "server.met",
    "nodes.dat",
    "cryptkey.dat",
    "preferences.dat",
    "clients.met",
    "known.met",
    "known2_64.met",
    "staticservers.dat",
    "shareddir.dat",
    "sharedfiles.dat",
    "Category.ini"
)

foreach ($f in $files) {
    $s = Join-Path $srcDir $f
    if (Test-Path $s) {
        Copy-Item -Path $s -Destination $destDir -Force
        $len = (Get-Item $s).Length
        Write-Host "  -> Copiado $f ($len bytes)" -ForegroundColor Gray
    }
}

# 2. Parsear preferencias clave (sección [eMule])
$prefContent = Get-Content (Join-Path $srcDir "preferences.ini")
$props = @{}
$currentSection = ""
foreach ($line in $prefContent) {
    $trimmed = $line.Trim()
    if ($trimmed -match "^\[(.*)\]$") {
        $currentSection = $matches[1]
    } elseif ($currentSection -eq "eMule" -and $trimmed -match "^([^=]+)=(.*)$") {
        $props[$matches[1].Trim()] = $matches[2].Trim()
    }
}

$port = if ($props["Port"]) { $props["Port"] } else { "19644" }
$udpPort = if ($props["UDPPort"]) { $props["UDPPort"] } else { "6591" }
$incoming = if ($props["IncomingDir"]) { $props["IncomingDir"] } else { "D:\Backup\Pendiente\" }
$temp = if ($props["TempDir"]) { $props["TempDir"] } else { "C:\Users\Windows\Downloads\eMule\Temp\" }
$maxUp = if ($props["MaxUpload"]) { $props["MaxUpload"] } else { "800" }
$maxDown = if ($props["MaxDownload"]) { $props["MaxDownload"] } else { "800" }
$nick = if ($props["Nick"]) { $props["Nick"] } else { "TauriMule" }

$amuleConf = @"
# aMule configuration file generated by TauriMule from eMule preferences
[eMule]
AppVersion=0.70b
Nick=$nick
QueueSize=50
MaxUpload=$maxUp
MaxDownload=$maxDown
Port=$port
UDPPort=$udpPort
UDPDisable=0
IncomingDir=$incoming
TempDir=$temp
ConnectToKad=1
ConnectToED2K=1
AutoConnect=1
Reconnect=1
MaxSourcesPerFile=400
MaxConnections=500
ServerKeepAliveTimeout=0
SmartIdCheck=1
FilterBadIPs=1
UseCreditSystem=1
SecureIdent=1
AllocateFullFile=0
AddNewFilesPaused=0

[ExternalConnect]
AcceptExternalConnections=1
ECAddress=127.0.0.1
ECPort=4712
ECPassword=5f4dcc3b5aa765d61d8327deb882cf99
RequireEncryption=0
AuthFailureWindowSeconds=60
AuthFailureThreshold=10
AuthLockoutSeconds=300

[WebServer]
Enabled=0

[AmuleApi]
Enabled=0
"@

Set-Content -Path (Join-Path $destDir "amule.conf") -Value $amuleConf -Encoding UTF8
Write-Host "Configuración importada exitosamente a $destDir\amule.conf!" -ForegroundColor Green
